plant: cournot # bathtub/cournot/rabbit
controller: AI # classic/AI

classic:
  Kp: 0.0
  Ki: 0.0
  Kd: 0.0

neural_net:
  layers: 5
  neurons_per_layer: 5
  weight_bias_initial_range: [-0.1, 0.1]
  activation_function: relu # sigmoid/tanh/relu

epochs: 100
timesteps: 50
learning_rate: 0.00005
noise: [-0.01, 0.01]

bathtub:
  A: 100
  C: 1
  H0: 10

cournot:
  p_max: 1
  cm: 0.1
  q_1: 0.0 # Initial value
  q_2: 0.1 # Initial value
  profit_target: 0.25

rabbit:
  initial_rabbits: 100
  rabbit_birth_rate: 0.4
  rabbit_eaten_rate: 0.4
  initial_wolves: 8
  wolf_death_rate: 2
  wolf_food_rate: 0.09
  target_rabbits: 80
