plant: bathtub # bathtub/cournout
controller: classic # classic/ai

classic:
  Kp: 0.5
  Ki: 0.5
  Kd: 0.5

neural_net:
  layers: 5
  neurons_per_layer: 10
  weight_bias_initial_range: [0, 1]
  activation_function: sigmoid # sigmoid/tanh/relu

epochs: 30
timesteps: 25
learning_rate: 0.05
noise: [-0.01, 0.01]

bathtub:
  A: 100
  C: 1
  H0: 10

cournout:
  pmax: 1000
  cm: 1
