plant: cournot # bathtub/cournot/rabbit
controller: AI # classic/AI

classic:
  Kp: 0.4
  Ki: 0.4
  Kd: 0.4

neural_net:
  layers: 5
  neurons_per_layer: 40
  weight_bias_initial_range: [-1, 1]
  activation_function: relu # sigmoid/tanh/relu

epochs: 50
timesteps: 25
learning_rate: 0.2
noise: [-1, 1]

bathtub:
  A: 100
  C: 1
  H0: 10

cournot:
  p_max: 1
  cm: 0.1
  q_1: 0.5 # Initial value
  q_2: 0.5 # Initial value
  profit_target: 0.5

rabbit:
  initial_rabbits: 100000
  rabbit_birth_rate: 0.7
  rabbit_eaten_rate: 0.03
  initial_wolves: 10
  wolf_death_rate: 0.1
  wolf_food_rate: 0.01
  target_rabbits: 2000
