plant: cournot # bathtub/cournot
controller: AI # classic/AI

classic:
  Kp: 0.04
  Ki: 0.03
  Kd: 0.03

neural_net:
  layers: 5
  neurons_per_layer: 10
  weight_bias_initial_range: [-20, 35]
  activation_function: relu # sigmoid/tanh/relu

epochs: 17
timesteps: 40
learning_rate: 0.05
noise: [-0.01, 0.01]

bathtub:
  A: 10000
  C: 2000
  H0: 213

cournot:
  p_max: 1
  cm: 0.1
  q_1: 0.5 # Initial value
  q_2: 0.5 # Initial value
  profit_target: 0.5
