plant: rabbit # bathtub/cournot/rabbit
controller: classic # classic/AI

classic:
  Kp: 500
  Ki: 29000
  Kd: 1000

neural_net:
  layers: 5
  neurons_per_layer: 5
  weight_bias_initial_range: [-0.1, 0.1]
  activation_function: tanh # sigmoid/tanh/relu

epochs: 50
timesteps: 50
learning_rate: 0.005
noise: [-0.01, 0.01]

bathtub:
  A: 100
  C: 1
  H0: 10

cournot:
  p_max: 1
  cm: 0.1
  q_1: 0.0 # Initial value
  q_2: 0.1 # Initial value
  profit_target: 0.25

rabbit:
  initial_rabbits: 200
  rabbit_birth_rate: 0.08
  rabbit_eaten_rate: 0.001
  initial_wolves: 1
  wolf_death_rate: 0.02
  wolf_food_rate: 0.00002
  target_rabbits: 15
