plant: bathtub # bathtub/cournout
controller: classic # classic/ai

neural_net:
  layers: 5
  neurons_per_layer: 10
  weight_bias_initial_range: [0, 1]
  activation_function: sigmoid # sigmoid/tanh/relu

epochs:
  training_epochs: 10
  timesteps_per_epoch: 100

learning_rate: 0.01
noise: [-0.01, 0.01]

bathtub:
  A: 0.5
  C: 0.1
  H0: 1

cournout:
  pmax: 1000
  cm: 1
