plant: cournot # bathtub/cournot
controller: classic # classic/ai

classic:
  Kp: 0.1
  Ki: 0.3
  Kd: 0.2

neural_net:
  layers: 5
  neurons_per_layer: 10
  weight_bias_initial_range: [0, 1]
  activation_function: sigmoid # sigmoid/tanh/relu

epochs: 20
timesteps: 25
learning_rate: 0.05
noise: [-0.01, 0.01]

bathtub:
  A: 100
  C: 1
  H0: 10

cournot:
  p_max: 0.9
  cm: 0.1
  q_1: 0.1 # Initial value
  q_2: 0.1 # Initial value
  profit_target: 0.5
